// Build: (1) inline ui/{index.html,styles.css,app.js} into one HTML string module,
// (2) bundle src/cli.ts into a single executable dist/berth.js with esbuild.
// Zero runtime dependencies: smol-toml is bundled in at build time.

import { chmodSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { build } from 'esbuild';

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const uiOnly = process.argv.includes('--ui-only');
const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));

function inlineUi() {
  const uiDir = join(root, 'ui');
  const read = (f) => (existsSync(join(uiDir, f)) ? readFileSync(join(uiDir, f), 'utf8') : '');
  let html = read('index.html');
  const css = read('styles.css');
  const js = read('app.js');
  if (!html) {
    html =
      '<!doctype html><html><head><meta charset="utf-8"><title>berth</title></head><body><p>ui not built</p></body></html>';
  }
  // The server injects a per-response CSP nonce into these two tags (see src/ui/server.ts).
  html = html.replace(
    /<link[^>]+href="\.\/styles\.css"[^>]*>/,
    () => `<style data-berth-inline>${css}</style>`,
  );
  html = html.replace(
    /<script[^>]+src="\.\/app\.js"[^>]*><\/script>/,
    () => `<script type="module" data-berth-inline>${js}</script>`,
  );
  mkdirSync(join(root, 'src', 'ui'), { recursive: true });
  const out = `// Generated by scripts/build.mjs. Do not edit.\nexport const PAGE_HTML: string = ${JSON.stringify(html)};\n`;
  writeFileSync(join(root, 'src', 'ui', 'page.generated.ts'), out);
  return { bytes: html.length };
}

// Keep the plugin manifest's version in step with package.json (tests enforce equality).
function syncPluginVersion() {
  const file = join(root, '.claude-plugin', 'plugin.json');
  let manifest;
  try {
    manifest = JSON.parse(readFileSync(file, 'utf8'));
  } catch {
    return; // no plugin manifest in this checkout
  }
  if (manifest.version !== pkg.version) {
    manifest.version = pkg.version;
    writeFileSync(file, `${JSON.stringify(manifest, null, 2)}\n`);
    console.log(`plugin: version synced to ${pkg.version}`);
  }
}

syncPluginVersion();
const ui = inlineUi();
console.log(`ui: inlined ${ui.bytes} bytes`);
if (uiOnly) process.exit(0);

mkdirSync(join(root, 'dist'), { recursive: true });
await build({
  entryPoints: [join(root, 'src', 'cli.ts')],
  outfile: join(root, 'dist', 'berth.js'),
  bundle: true,
  platform: 'node',
  target: ['node20'],
  format: 'esm',
  banner: { js: '#!/usr/bin/env node' },
  define: { __BERTH_VERSION__: JSON.stringify(pkg.version) },
  legalComments: 'inline',
  minify: false,
  sourcemap: false,
  logLevel: 'warning',
});
chmodSync(join(root, 'dist', 'berth.js'), 0o755);
console.log(`built dist/berth.js (${pkg.version})`);
